---
deployment:
  tasks:
    # Remove old files from mocfurni.shop
    - export DEPLOYPATH=/home/eal236bnt9pe/client/
    - /bin/rm -rf $DEPLOYPATH*

    # Copy new build files to public_html
    - /bin/cp -R .output/public/* $DEPLOYPATH

    # Set proper permissions
    - /bin/chmod -R 755 $DEPLOYPATH
